full_rebuild: true
port: 4343
name: Nome Do Site
description: um site legal
destination: jekyllbuild
url: #place url
baseurl: #place folder name if site is served in subfolder
permalink: /:title/
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #change to false if you want to use pagination
gems: [jekyll-paginate]
media_folder: /media
tumblr: "#"
pinterest: "#"
instagram: "#"
twitter: "#"
facebook: "#"
youtube: "#"
vimeo: "#"
soundcloud: "#"

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-full"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, jekyllbuild]
