name: FluidLab
description: Curadoria em brinquedos er√≥ticos
featimg: homecover.jpg

url: http://meuSite.com
baseurl: '/BrunnaRosa'
port: 4343
permalink: /:title/
include: ['_pages']

media_folder: /media
destination: jekyllbuild
full_rebuild: true
gems: [jekyll-paginate]
paginate: 8
paginate_path: /page/:num/
infinite_scroll: true #false for pagination

tumblr: "#"
pinterest: "#"
instagram: "#"
twitter: "#"
facebook: "#"
youtube: "#"
vimeo: "#"
soundcloud: "#"

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page-full"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post-full"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
include: ['_pages']
exclude: [.git, .gitignore, .sass-cache, README.md, jekyllbuild]
